### ISSUE TITLE
Question about statusline in screenshot

### ISSUE THREAD

**Issue by inukshuk** [ntk148v/komau.vim#1]
This is a great theme, thanks for sharing! I was wondering about the accompanying power/air/light line theme in the screenshots: is that published somewhere? The round edges are an interesting touch, especially now that many GTK apps come with rounded window corners at the bottom. Can you tell me which status line plugin this is? Thanks!

**Comment by ntk148v** [comment]
@inukshuk Hi, this is [bubbles lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/examples/bubbles.lua) 🥂

**Comment by inukshuk** [comment]
Thanks!
