### ISSUE TITLE
Can we disable the italic text?

### ISSUE THREAD

**Issue by aerosayan** [ntk148v/komau.vim#3]
Hello, thanks for sharing the color-scheme. I love it.

Is there any way to disable the italics?

The font I'm using (Victor Mono) does not have good italic fonts, and so the code becomes difficult to read.

If there was any configuration option to disable the italics, it would be helpful.

Thanks!

![colorscheme](https://github.com/ntk148v/komau.vim/assets/39849461/f26884cd-7f0a-4673-a709-076546576823)

**Comment by ntk148v** [comment]
Hi @aerosayan,

I've pushed new options, get the newest version of `komau.vim` and try these options 🥂 

```vim
" Disable italic, enable by default
let g:komau_italic=0
" Disable bold, enable by default
let g:komau_bold=0
```

**Comment by aerosayan** [comment]
@ntk148v Thanks! It worked well!

![screen](https://github.com/ntk148v/komau.vim/assets/39849461/3fe00b64-292e-481c-a0f0-16fe3f475a68)

**Comment by aerosayan** [comment]
@ntk148v Also, the red accent color you used, is really nice!

I modified the colorscheme little bit, and used it for the functions.

![modified-colorscheme](https://github.com/ntk148v/komau.vim/assets/39849461/cd377f6d-028c-4048-ba8e-6fc8f669185c)
